'use client'


//THIS WILL BE POP UP WHEN NEW WORKOUT IS BEING MADE
// WILL SHOW CURRENTLY MADE OR NONE ROUTINES
// GIVe BLANK AND A DASHED OUTLINE TO CREATE A NEW ROUTINE ("Upper")



export default function Routines()
{
    
}