'use client'

//THIS POPS UP WHEN THEY SELECT TO START A ROUTINE
// JUST SHOW THE LIST OF EXERCISES IN THE ROUTINE
// VERY SIMILAR TO HEVY
// ADD A SECTION FOR EACH MOVEMENT AND TRACK REPS AND STUFF


export default function WorkoutTracker()
{
    
}